server:
  port: 8081
  servlet:
    encoding:
      charset: utf-8
      force: true

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/bank?serverTimezone=Asia/Seoul
    username: root
    password: tongtong2*

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      '[hibernate.default_batch_fetch_size]' : 100
      '[hibernate.format_sql]': true
    show-sql: true
  output:
    ansi:
      enabled: always

logging:
  level:
    '[shop.mtcoding.bank]': DEBUG
    '[org.hibernate.type]': TRACE
